### ISSUE TITLE
Previous searching result should not be displayed in the grid.

### ISSUE THREAD

**Issue by LeilaWang2** [929lwang1/SCPDemo201904#10]
Repro Steps:
1. Search name containing "1". select a resource group and close the search form.
2. Launch Search form again, the searching result in step 1 is still displayed. This is incorrect.

**Comment by 929lwang1** [comment]
Assigning to myself.

**Comment by 929lwang1** [comment]
Fixed it under commit ddd6e84532fee84e06dbcab401ed7405a7357ec5.
Tested locally with above steps. The previous search results are no longer listed in the Search form when I launch it for the second time. 
Please review and let me know if there's any question.

**Comment by LeilaWang2** [comment]
The reported issue is fixed

**Comment by LeilaWang2** [comment]
If I close the searching form through clicking X in the upper right corner instead of the Close button, the previous searching results and searching parameters are still displayed. Please review the problem.
![image](https://user-images.githubusercontent.com/49714253/56424016-0f938300-62e1-11e9-98ac-4df2216b6b8c.png)

**Comment by 929lwang1** [comment]
Fixed it under commit fa04afcc97ab90719d4f53ef3fe622640f70253e.
Tested locally with above steps. Now the search grid and other fields value can be reset properly when we exit the window with 'X' button and launch it again.
Also fixed the search button when launching the screen for the second time.
Please review and let me know if there's any question. Thanks

**Comment by LeilaWang2** [comment]
Exit the search form by "X" button and reopen it. No old search result is shown.
