### ISSUE TITLE
Selected resource group cannot move up/down with the scrollbar

### ISSUE THREAD

**Issue by LeilaWang2** [929lwang1/SCPDemo201904#15]
Repro steps:
1.  Open Select form and select a resource group like '01-IR2'.
2. Secondly, use the mouse to scroll down and you will find the second record is selected. As following picture shows:
This is incorrect, the first selected record '01-IR2' should not always be selected as user scroll.
![image](https://user-images.githubusercontent.com/49714253/56334506-2ba50080-61cb-11e9-82e9-cece5c6b14c9.png)

**Comment by 929lwang1** [comment]
This is a common issue for all three grid in our demo, i.e. add resource grid, resource grid, search grid.
Did some research and also discussed this with Kerry.
We decide to skip this issue for now. Thanks.

**Comment by LeilaWang2** [comment]
Close this issue because we cannot realize it in delphi IDE for now.
