### ISSUE TITLE
Order By and Goto under Search menu does not work

### ISSUE THREAD

**Issue by LeilaWang2** [929lwang1/SCPDemo201904#16]
The orderby and goto function under the search menu totally not work. 
1. If I select name or description, there should be a check mark on it.
2. Hotkey ctrl+right/left and Alt+right/left can not work.

**Comment by lunachenapt** [comment]
make order by and goto work. Also remenber the order by selection when reopen

**Comment by LeilaWang2** [comment]
1. Order By and Goto tool under Select menu can work properly as in the tool bar.
2. Hotkey pressing is allowed.
3. Goto options are displayed with proper enable/disabled state.
