### ISSUE TITLE
The navigation buttons should be disabled after removing resources from a resource group

### ISSUE THREAD

**Issue by LeilaWang2** [929lwang1/SCPDemo201904#18]
Repro Steps:
1. Remove a resource from a resource group like "01-FR1_FR2".
2. The navigation buttons are still enabled, this is incorrect.

![image](https://user-images.githubusercontent.com/49714253/56347292-8acc3a80-61f6-11e9-90f4-20f0035ef142.png)

**Comment by ctt123123** [comment]
Assign to myself.

**Comment by ctt123123** [comment]
Fix it and wait for committing.

**Comment by ctt123123** [comment]
Fix it under 12a68d7ad64784293580ecf49865ca34d71c2a38

**Comment by LeilaWang2** [comment]
Tested ok. After a resource removed, the resource group is in Update mode properly.
