### ISSUE TITLE
The operation cost value which has a decimal turns to 0 after saving the change.

### ISSUE THREAD

**Issue by LeilaWang2** [929lwang1/SCPDemo201904#19]
Repro steps:
1. Update the operation cost for a resource group like "M100" to 20.5 .
2. After clicking save button, the displayed operation cost is still 20.5.
3. But after clicking next and previous button to refresh, the operation cost field becomes 0.
![image](https://user-images.githubusercontent.com/49714253/56350605-c3234700-61fd-11e9-881e-b65749bf21c1.png)

![image](https://user-images.githubusercontent.com/49714253/56350618-c6b6ce00-61fd-11e9-892d-3a75fbbcae68.png)

**Comment by ctt123123** [comment]
Assigning to myself.

**Comment by ctt123123** [comment]
The field is stored as an integer, so the decimal cannot be stored in the field. I am not sure how to fix it. After my research, TJvSpinEdit is a part of the JEDI Visual Component Library, and it has a property called ValueType which we can set to vtFloat. Leaving it for now.

**Comment by ctt123123** [comment]
No code changes for this issue. Please do not test with decimals.

**Comment by LeilaWang2** [comment]
The control of Operation Cost(per hour) in Delphi does not support reading decimal values.
