### ISSUE TITLE
close search form when double click a row with 'Close On Go' turned ON

### ISSUE THREAD

**Issue by 929lwang1** [929lwang1/SCPDemo201904#2]
With 'Close Window On Go' turned ON in Search form, when double click on a row, the Search Form should be closed, just like what is done when click Go button. @929lwang1 
![1-search-closeongo](https://user-images.githubusercontent.com/49431914/56256976-62144a00-60fd-11e9-8a5d-75d1b4ad8873.png)

**Comment by 929lwang1** [comment]
Fixed under commit # edaeb5a, with its exe file and release notes committed under commit # a1c6ab1.
With this commit, if we turn ON ‘Close Window On Go’ in Search form, double clicking a selected row will do two things below:
1.	Close the search form.
2.	Display the selected resource group in the Resource Group screen if the previous resource group record is not updating. Otherwise, the resource group screen will remain AS IS.

Other update in this commit:
Move button events to actions. This is only visible in programming side. The screen function should work  AS IS.

**Comment by 929lwang1** [comment]
Reopening this just to make sure it can go through testing in QA side.

**Comment by LeilaWang2** [comment]
1. With 'Close Window On Go" selected, double clicking a row will close the search form.
2. If the currently displayed resource group is not being edited, it will display the selected resource group. Else, the selected resource group won't be displayed.
