### ISSUE TITLE
Search form - search grid column sequence with different filters

### ISSUE THREAD

**Issue by 929lwang1** [929lwang1/SCPDemo201904#20]
In Search form, when find records with criteria ‘Name’, the grid’s column order should be Name and then Description.
When find records with criteria ‘Description’, the grid’s column order should be Description and then Name.
![2-search-grid](https://user-images.githubusercontent.com/49431914/56354385-287b3600-6206-11e9-88e3-d1bd274a54eb.png)

**Comment by 929lwang1** [comment]
Assigning to myself. Will work on this tomorrow.

**Comment by 929lwang1** [comment]
Fixed it under commit cb8d4a0934fa722546613be65b233ac27282b78e, along with some other enhancements in Search form.

Tested locally with the following steps. Worked fine. 
T1. Launch Search form. Its default filter is ‘Name’ + ‘Starts With’. Click Search button with filter ‘Name’ + ‘Contains’ + ‘01’. A list of records, ordering by Name, show up in the grid, with ‘Name’ as the first column and ‘Description’ as the second column.
T2. Change the filter to be ‘Description’ + ‘Ends With’ + ‘2’, and hit Search button again. A list of records which ends with ‘2’, ordering by Description, show up in the grid, with ‘Description’ as the first column and ‘Name’ as the second column.
T3. Close the Search form, and launch it again. Its default filter is still ‘Name’ + ‘Starts With’. And the latest filter value ‘2’ is also displayed by default. The grid has 'Name' as the first column and 'Description' as the second column.

Other enhancement: Name/Description & Starts With/Contains/Ends With fields do not allow editing.

Please review and let me know if there’s any question. Thanks.

**Comment by LeilaWang2** [comment]
The enhancements are implemented properly.
