### ISSUE TITLE
No error message appears when entering a duplicate resource name

### ISSUE THREAD

**Issue by victoriawang0** [929lwang1/SCPDemo201904#21]
1. Click New
2. Enter a duplicate resource name which already exists
3. Click Save, no message appears and the Save button doesn't work. There should be an error message displayed. "Entity already exists in database; cannot save."

**Comment by TedWang-Paddington** [comment]
a517c857ca3c635bf49613e4c303b5dfcc5b670e

**Comment by victoriawang0** [comment]
Issue is not fixed. 
Enter a duplicate resource name which already exists, click Save, no message appears and the Save button doesn't work. There should be an error message displayed. "Entity already exists in database; cannot save."

**Comment by TedWang-Paddington** [comment]
7f2d3e7

**Comment by victoriawang0** [comment]
Issue is finished. And the error message priority is,
1. name field cannot be blank.
2. a group must contain at least one resource.
3. Entity already exists in database; cannot save.
