### ISSUE TITLE
Can we get rid of the pop-up error message when double clicking in a blank search results grid.

### ISSUE THREAD

**Issue by LeilaWang2** [929lwang1/SCPDemo201904#22]
Repro Steps:
1. In search form, before clicking search button, try to double click anywhere in the search results grid, the following error will pop up:
![image](https://user-images.githubusercontent.com/49714253/56424809-63539b80-62e4-11e9-810e-23ba351d3644.png)

2. In search form, search name that starts with 9 and the search results grid is empty. Double clicking anywhere in the grid will trigger the following error:
![image](https://user-images.githubusercontent.com/49714253/56424814-68184f80-62e4-11e9-9e85-66a8ae916cf5.png)

**Comment by ctt123123** [comment]
Assign to myself.

**Comment by ctt123123** [comment]
Fix it under 1ffe8956b7ff8b162d075200afdecb84910f6588, now there are no error messages when double clicking in a blank search results grid.

**Comment by LeilaWang2** [comment]
1. The error message no more pops up when double clicking on a blank grid. 
2. However, I found that if the "Close Window on Go" is selected, double clicking on a blank grid would close the form automatically. I checked it in a RossSCP and double click will not shut the form if the grid is blank. Could you have a review on this problem?

**Comment by ctt123123** [comment]
Fix issue when doubling click a blank grid the search form will be closed under 00299c8d9f2a0157417af7bfc932ef846c2c770d.

**Comment by LeilaWang2** [comment]
Issue was fixed properly.
