### ISSUE TITLE
Met "conversion failed**"error after clicking add button to add resource.

### ISSUE THREAD

**Issue by LeilaWang2** [929lwang1/SCPDemo201904#23]
Repro steps;
1. Launch resource group and click search button firstly.
2. Search  name by containing '1'. Select "A1" and close the resource group.
3. Click Add button for the "A1" to add resource "IR1".
![image](https://user-images.githubusercontent.com/49714253/56492887-bbc2ad00-651f-11e9-9307-31cb102c2133.png)
![image](https://user-images.githubusercontent.com/49714253/56492899-c54c1500-651f-11e9-9873-47a6ab28ccd6.png)
4. Try to click add button to add another resource. The error pops out:
![image](https://user-images.githubusercontent.com/49714253/56492930-de54c600-651f-11e9-9411-07b7bb11d16d.png)

**Comment by lunachenapt** [comment]
Fix error when add twice

**Comment by LeilaWang2** [comment]
The error no longer pops up when trying to add resource(s).
