### ISSUE TITLE
No search result can be returned on a search form launched not for the first time.

### ISSUE THREAD

**Issue by LeilaWang2** [929lwang1/SCPDemo201904#24]
Repro steps:
1. In Resource Group, launch search form for the first time.
2. Search name that starts with "n". Search results are displayed properly. Just click Close button.
2. Launch search form again, and search name that starts with "a". No search result is displayed. This is incorrect.

**Comment by ctt123123** [comment]
Assign to myself.

**Comment by 929lwang1** [comment]
This has been fixed under commit fa04afcc97ab90719d4f53ef3fe622640f70253e.
Please review and let me know if there's any question. Thanks.

**Comment by LeilaWang2** [comment]
Searching function works well now.
