### ISSUE TITLE
Make column name and form title standard in Add Resource(s) form

### ISSUE THREAD

**Issue by LeilaWang2** [929lwang1/SCPDemo201904#25]
1. We need to modify the caption of the columns to "Resource Name" and "Resource Description"
2. The title of the form need to be changed to "Add Resource(s)".
![image](https://user-images.githubusercontent.com/49714253/56548817-b4e57a00-65b3-11e9-9d3a-9476f8130e27.png)

**Comment by ctt123123** [comment]
Fix it under d96218db5adb94b11758b05266646d13a7ac47a9, now the column name and title can display correctly.

**Comment by LeilaWang2** [comment]
Changes are implemented
