### ISSUE TITLE
Displayed resource group is not updated to the one updated by someone else.

### ISSUE THREAD

**Issue by LeilaWang2** [929lwang1/SCPDemo201904#26]
2 people has launched the resource group linked to the same DB. After one of them updated a resource group, the other one failed to view the updated resource group.
Repro steps:
1. I launched resource group in my desktop and remote server. Currently, the description of resource group "April" is "rename it from 852 and check"
2. In my local computer, I updated the description for "April" to "rename it from 852 and check-1".
3.  In remote server, search the resource group name by starting with 'a'. In the search result grid, the description of "April" is the updated one "rename it from 852 and check-1" which is proper. 
4. Then select "April" to view it in resource group form, the description field still displays "rename it from 852 and check". I think we are able to make the displayed resource group show the updated version by other people.
![image](https://user-images.githubusercontent.com/49714253/56556410-8cb54580-65ca-11e9-81e9-2ac280ca0bda.png)

**Comment by TedWang-Paddington** [comment]
Still cannot refresh the records, ask Kerry tomorrow

**Comment by TedWang-Paddington** [comment]
Talked with Kerry, no need to fix this issue. Please help close it.

**Comment by LeilaWang2** [comment]
Close this issue because RossSCP lack the ability to detect and catch the updates from other users.
