### ISSUE TITLE
Clicking Close button should get the same message as clicking Exit button

### ISSUE THREAD

**Issue by victoriawang0** [929lwang1/SCPDemo201904#27]
1. Edit the resource group in new/update mode
2. Click close button, the whole form is closed. There should be a confirm message like the following.
![image](https://user-images.githubusercontent.com/49432059/56576371-c1d98c00-65fa-11e9-9e70-ae3d6efdc373.png)

**Comment by TedWang-Paddington** [comment]
d89d9fe

**Comment by victoriawang0** [comment]
Issue is fixed. 
Edit the resource group in new/update mode, click close button, the same message will be popped up as clicking Exit button.
