### ISSUE TITLE
Clicking in the space of time input box will move the cursor to the last digit.

### ISSUE THREAD

**Issue by LeilaWang2** [929lwang1/SCPDemo201904#28]
Repro steps:
1. In the new or update mode of resource group, click in the space o time field.
![image](https://user-images.githubusercontent.com/49714253/56857816-64e82800-69a4-11e9-94ca-d0e3c7ab7bf9.png)
2. The cursor is located at the end of the number. It is supposed to be located in the beginning of the time.
![image](https://user-images.githubusercontent.com/49714253/56857833-99f47a80-69a4-11e9-9acf-503904850747.png)

**Comment by ctt123123** [comment]
Fix the issue under 80894c730a4d46591cf7c65e3bcef9b78a087988, now when clicking in the space of time input box will move the cursor to the beginning.

**Comment by LeilaWang2** [comment]
The issue was fixed in ResourceGroupClient-20190429-1343.
