### ISSUE TITLE
Fail to update the description of a resource group.

### ISSUE THREAD

**Issue by LeilaWang2** [929lwang1/SCPDemo201904#29]
Test in "ResourceGroupClient-20190428-0901"
Repro steps:
1. Search and view the resource group"A1", then try to edit the description field and save, and the description field still displays the old value after clicking save button.
2. Search and view the resource group "88", then try to assign a value to the blank description field, and the description field remains blank after clicking save button.

**Comment by LeilaWang2** [comment]
The name of resource group cannot be edited neither.

**Comment by 929lwang1** [comment]
The key point of recreating this issue is to directly click Save button right after we change the value of Description field, WITHOUT LEAVING this field first.

**Comment by 929lwang1** [comment]
Fixed it under commit 98c72959163405ce2fc5cca0f5750c780e03c68e.
Tested locally with above steps. Works fine.
Please review and let me know if there's any question. Thanks.

**Comment by LeilaWang2** [comment]
The issue was fixed in ResourceGroupClient-20190429-1343.
