### ISSUE TITLE
Navigation buttons become enabled after clicking New and Clicking Cancel

### ISSUE THREAD

**Issue by victoriawang0** [929lwang1/SCPDemo201904#3]
When we are inquiring the first resource group record, first and previous buttons are disabled, if clicking New and clicking Cancel, first and previous buttons should be disabled as before, but they become enabled. Only after clicking one of them again, they become disabled.

When we are inquiring the last resource group record, last and next buttons are disabled, if clicking New and clicking Cancel, last and next buttons should be disabled as before, but they become enabled. Only after clicking one of them again, they become disabled.

**Comment by lunachenapt** [comment]
Fix the navigation button state when do new and cancel

**Comment by victoriawang0** [comment]
Finished testing. Issue is fixed.
