### ISSUE TITLE
Searching the same value for the second time cannot return results

### ISSUE THREAD

**Issue by LeilaWang2** [929lwang1/SCPDemo201904#30]
Repro steps:
1. Launch Search form for the first time, search names that start with "a" and get 6 record. Close the search form.
![image](https://user-images.githubusercontent.com/49714253/56858547-5141bf00-69ae-11e9-9440-dd8e3d13ae2d.png)

2. Launch search form again, and just click search button with the default search history, No search result can be returned.
![image](https://user-images.githubusercontent.com/49714253/56858550-54d54600-69ae-11e9-92de-646c617b228d.png)

**Comment by 929lwang1** [comment]
Working on this.

**Comment by 929lwang1** [comment]
Cannot recreate it. Works fine in my testing. Will talk to Leila.

**Comment by 929lwang1** [comment]
Confirmed with Leila that this issue has already been fixed by ResourceGroupClient-20190428-1336.exe.
Under commit a7acf9886a913b9da189c7efad3847cb5ac6c4a8.

**Comment by LeilaWang2** [comment]
The issue was detected in ResourceGroupClient-20190428-0901, but the Issue was gone in "ResourceGroupClient-20190428-1336"
