### ISSUE TITLE
Cannot adjust the operation cost value with Up/Down key

### ISSUE THREAD

**Issue by LeilaWang2** [929lwang1/SCPDemo201904#31]
Up and Down key should function the same as clicking increase/decrease control on the form.
Repro steps:
1. For instance, the operation cost for "Bubble" is 8.
2.a If I select the operation cost field and press Up key, the operation cost is changed to 1 which should be 9.
2.b If I select the operation cost field and press Down key, the operation cost is changed to 0 which should be 7.

**Comment by lunachenapt** [comment]
It could not remove the original Up and Down key action for the spinedit. We may not support key  now only could using click action

**Comment by lunachenapt** [comment]
Add up down key action for cost

**Comment by LeilaWang2** [comment]
Issue was fixed in ResourceGroupClient-20190429-1343.
