### ISSUE TITLE
Save and Cancel button become enabled after the click in the cost and time fields.

### ISSUE THREAD

**Issue by LeilaWang2** [929lwang1/SCPDemo201904#32]
Repro Steps:
1. View the resource group "April", click the operation cost field and then click  anyone of the 4 time setup fields. The save and cancel button become enabled. This is improper.
![image](https://user-images.githubusercontent.com/49714253/56859830-d46d1000-69c2-11e9-84e7-6433642eb025.png)

**Comment by lunachenapt** [comment]
Do not call onchange procedure when leaving cost without change

**Comment by LeilaWang2** [comment]
Issue was fixed in "ResourceGroupClient-20190429-1343"
