### ISSUE TITLE
Remove a resource and click save, error message appears.

### ISSUE THREAD

**Issue by victoriawang0** [929lwang1/SCPDemo201904#33]
Recreation steps:
1. New a resource group, set operation cost as 2 decimals, add two resources on it, and save.
2. Remove one resource, and click save.
The record cannot be saved with the following error message displayed.
![image](https://user-images.githubusercontent.com/49432059/56860762-b3a9b800-69cc-11e9-92c0-1b50a5e9f81a.png)

**Comment by 929lwang1** [comment]
Fixed it under commit 98c72959163405ce2fc5cca0f5750c780e03c68e.
Tested locally with above steps. Works fine.
Please review and let me know if there's any question. Thanks.

**Comment by victoriawang0** [comment]
Issue is fixed. The error message will not be displayed when trying the recreation steps above. Close this issue.
