### ISSUE TITLE
Error message appears when clearing Operation Cost and leave it

### ISSUE THREAD

**Issue by victoriawang0** [929lwang1/SCPDemo201904#34]
1. In New /Edit mode
2. Clear Operation Cost field
3. Click any place in the form
The following error message appears.
![image](https://user-images.githubusercontent.com/49432059/56875240-02f5f400-6a72-11e9-8194-699a9d3a49ca.png)

**Comment by lunachenapt** [comment]
Allow cost as null

**Comment by victoriawang0** [comment]
1. Clear Operation Cost field, click up/down button, or hit up/down key, this error message is still shown.
2. When click new, the initial value of  Operation Cost field should have 2 decimals.

**Comment by lunachenapt** [comment]
Fix error also set decimal when new

**Comment by victoriawang0** [comment]
Issue is fixed.
