### ISSUE TITLE
Deleting the operation cost does not work properly.

### ISSUE THREAD

**Issue by LeilaWang2** [929lwang1/SCPDemo201904#35]
In new mode, blank operation cost is saved as "0", which could cause error message. In update mode, blank operation cost cannot be saved.
**Repro steps:**
Test in ResourceGroupClient-20190429-1343.
1. New a resource group "Sears" with operation cost field blank. After clicking save button, then navigate back and forth to check the new resource group, the operation cost become "0". I think it should be blank (same as what the SCP does) or "0.00".
![image](https://user-images.githubusercontent.com/49714253/56879848-11053e00-6a8d-11e9-9407-69959fd2331e.png)
![image](https://user-images.githubusercontent.com/49714253/56879858-15c9f200-6a8d-11e9-8553-e54809150378.png)
2. Delete the operation cost of resource group "Bubble". After clicking save button, then navigate back and forth to check the updated resource group, the operation cost is still "8.00". I think it should be blank (same as what the SCP does) or "0.00".

**Comment by lunachenapt** [comment]
could save null cost . when new show 0.00

**Comment by LeilaWang2** [comment]
The null cost can be saved as blank when creating or updating a resource group.
