### ISSUE TITLE
Add Resources form - selecting a row only selects resource column

### ISSUE THREAD

**Issue by victoriawang0** [929lwang1/SCPDemo201904#37]
1. New a resource group
2. Click Add button, Add Resources form shows up.
3. Select a row, but only resource name column is selected. The whole record row should be selected, just as that in SCP.
![image](https://user-images.githubusercontent.com/49432059/56881396-d9999000-6a92-11e9-9524-17cadce0a06d.png)

**Comment by lunachenapt** [comment]
Show select when select a row

**Comment by victoriawang0** [comment]
Issue is fixed. Select a row, the whole record row is selected.
