### ISSUE TITLE
Error appears when creating the second resource group and adding resource group 

### ISSUE THREAD

**Issue by victoriawang0** [929lwang1/SCPDemo201904#4]
![1](https://user-images.githubusercontent.com/49432059/56267363-268b7700-6121-11e9-97c1-2f3ac0c2652e.png)

Click OK on this error message, then click Add again, Resource IR3 and SR5 will be added on grid automatically, and Add resource form is opened as well.

![image](https://user-images.githubusercontent.com/49432059/56267552-b7625280-6121-11e9-8e9b-193aef4febf6.png)

**Comment by victoriawang0** [comment]
Then the record cannot be created successfully with this error message keeping popping up.

**Comment by 929lwang1** [comment]
Fixed it under commit 35342121832f9000f05c9f322252d41f04534da8.
Please review and let me know if there's any question. Thanks.

**Comment by victoriawang0** [comment]
Finished testing, this issue is fixed and this error never appears as per the recreation steps.
