### ISSUE TITLE
Search grid is not refreshed correctly when switching search filters

### ISSUE THREAD

**Issue by 929lwang1** [929lwang1/SCPDemo201904#5]
Search grid is not refreshed correctly when switching search filters between Name and Description.

Steps to recreate:
1. Open Search form, and hit search button with filter below:
Description + Contains + abc
Nothing shows up in the grid. Correct.

2. Change the search criteria to Name + Contains + 01, and hit Search button again. There are 10 records in the grid, whose name contains 01. Correct.

3. Change the search criteria to Description + Contains + abc, and hit Search button again. There are still 10 records in the gird. Incorrect. The grid should be blank.

[Issue2-SearchByDesc.docx](https://github.com/929lwang1/SCPDemo201904/files/3088280/Issue2-SearchByDesc.docx)

**Comment by 929lwang1** [comment]
Fixed in commit 168624e01a77921a459aae105f8454b961b03baa.
Tested with above steps. Now the research grid can be refreshed properly when switching the filter between Name and Description.
Please review and let me know if there's any question. Thanks.

**Comment by LeilaWang2** [comment]
The issue was fixed properly. The searching results do not contain the results for last time any more.
