### ISSUE TITLE
No need to display this message after canceling deletion operation

### ISSUE THREAD

**Issue by victoriawang0** [929lwang1/SCPDemo201904#6]
![image](https://user-images.githubusercontent.com/49432059/56267962-dc0afa00-6122-11e9-8d9a-bffc3a37e028.png)

**Comment by victoriawang0** [comment]
![image](https://user-images.githubusercontent.com/49432059/56276784-bcc99800-6135-11e9-967f-050854ed1bab.png)
Remove this deletion successfully message as well.

**Comment by ctt123123** [comment]
Assign to myself.

**Comment by ctt123123** [comment]
Delete unnecessary messages and wait for committing.

**Comment by ctt123123** [comment]
Fix it under 12a68d7ad64784293580ecf49865ca34d71c2a38

**Comment by victoriawang0** [comment]
No unnecessary messages will be displayed after canceling deletion operation or deletion.
