### ISSUE TITLE
Error message should appear if leaving Required field blank

### ISSUE THREAD

**Issue by victoriawang0** [929lwang1/SCPDemo201904#7]
If leaving Name or Utilization field blank, click Save button, it doesn't work. But there should be an error message appearing to tell you that "XXX cannot be blank."

**Comment by 929lwang1** [comment]
Assigning to myself. Working on it right now.

**Comment by 929lwang1** [comment]
This has been fixed under commit 35342121832f9000f05c9f322252d41f04534da8 & commit 60d2cfa08022ef400730df168850e3b9cf63d4ec.
Tested locally. Now the Utilization Type is automatically populated and could not be blank. If we hit Save button with blank Name, an error message 'Field Name cannot be blank.' pops up.
Please review and let me know if there's any question. Thanks,

**Comment by LeilaWang2** [comment]
I can still save a resource group with blank name.
Repro Steps in 20190423-0917.
1. Delete the name on a resource group and click save button. The resource group can be saved with blank name.
![image](https://user-images.githubusercontent.com/49714253/56558153-4e228980-65d0-11e9-9519-1522c73059e7.png)

2. Then try to assign a name to the resource group and click save button, the error message  'Field Name cannot be blank.' just pop out.
![image](https://user-images.githubusercontent.com/49714253/56558213-8924bd00-65d0-11e9-8849-afae49be490c.png)

**Comment by victoriawang0** [comment]
This issue is fixed under Issue # 21 No error message appears when entering a duplicate resource name.
