### ISSUE TITLE
Text field format issues

### ISSUE THREAD

**Issue by victoriawang0** [929lwang1/SCPDemo201904#8]
1. negative value should not be allowed to enter, instead of showing the internal error message.
![image](https://user-images.githubusercontent.com/49432059/56275076-981ff100-6132-11e9-82ee-ea2f1de5308e.png)
2. Operation cost and four Time fields should allow at least 2 decimals.
3. Characters and symbols should not be allowed to enter in Preparation /Cleanup Time field.
4. Add automatic conversion when changing the time units in Preparation /Cleanup Time field.
5. Spaces in the beginning of text should be removed after the record is created.

**Comment by lunachenapt** [comment]
1. value could assign correctly when exceed min max error, but error message could not remove, seem it is set in control spinedit. Fix in issue 33 in excel

**Comment by lunachenapt** [comment]
1. remove the error message, it is working ok now. Fixed in 34 in excel.

**Comment by ctt123123** [comment]
Fix #3 and #5 under 258081547deb99b3bf06a5a497b720c45f697f42, and #4 works fine.

**Comment by lunachenapt** [comment]
Fix #2 Operation cost can allow 2 decimal

**Comment by lunachenapt** [comment]
Fixed #5

**Comment by victoriawang0** [comment]
All 5 issues have been fixed.
