### ISSUE TITLE
OK button is always disabled after selecting the resource in Add Resource form

### ISSUE THREAD

**Issue by victoriawang0** [929lwang1/SCPDemo201904#9]
![image](https://user-images.githubusercontent.com/49432059/56276067-70ca2380-6134-11e9-81a3-fd71c6ea34ac.png)

This issue happens when you New a resource group, will not happen when editing an existing resource group.

**Comment by lunachenapt** [comment]
Enable ok button after selecting a record

**Comment by 929lwang1** [comment]
Reopening this just to make sure it can go through testing in QA side.

**Comment by victoriawang0** [comment]
Finished testing, OK button is enabled after you select another record in Add Resource form.
An additional issue is, in SCP, edit an existing resource group to add resource, no record is selected by default, so OK button is disabled, after you select one record, OK button becomes enabled.
But in our procedure, the first record is always selected and OK button is disabled.

**Comment by lunachenapt** [comment]
Do not select the first line when open

**Comment by victoriawang0** [comment]
Issue is fixed.
